Выполнено задание "Шаблонизируй это"
htmlacademy-ecmascript/1761943-cinemaddict-15 pull request #4
Opened 2021-08-04 13:44 UTC by Tatiaynti

Добавлены структуры данных, описывающие миникарточку фильма и попап фильма, комментарий.
В шаблоны добавлены данные.
Реализована работа кнопки Show more.

2021-08-05 10:54 UTC, ademaro commented on src/mock/film.js
> +    runtime: `${runtimeHours}h ${runtimeMins}m`,
можем в моках генерировать просто число — количество минут, а в шаблоне форматировать уже как нужно

2021-08-05 10:55 UTC, ademaro commented on src/mock/film.js
> +const films = new Array(FILM_CARDS_COUNT).fill().map(generateFilm);
генерацию самих фильмов — в main.js 

можно сделать именно generateFilms()

2021-08-05 10:57 UTC, ademaro commented on src/mock/film.js
> +const getFavorites = () => {
во-первых это уже не моки, надо отдельно вынести это функционал
во-вторых — попробуй через методы массивов (filter, reduce, ...)

2021-08-05 11:00 UTC, ademaro commented on src/mock/popup.js
> +
отдельная мока для попапа?) Это же тот же самый фильм, просто расширенные поля, которые не показываются в списке (но по факту это тот же самый фильм будет открываться, что и в общем списке. Предлагаю объединить с mock/film.js, просто в шаблоне в списке фильмов будем не все поля показывать

2021-08-05 11:01 UTC, ademaro commented on src/mock/utils.js
> +const FILM_CARDS_COUNT = 18;
почему в моках? давай так же в main, там мы определяем сколько хотим нагенерить фильмов

2021-08-05 11:03 UTC, ademaro requested changes
В целом — очень хорошо! Ты молодец! Давай совсем чутка подправим что бы не тащить дальше и я закрою ПР

2021-08-07 15:24 UTC, ademaro commented on src/mock/film.js
> +  return dayjs(day).format('DD MMMM YYYY');
давай дату «сырую» хранить будем, без форматирования

2021-08-07 15:26 UTC, ademaro approved these changes
окай, летим дальше, но думаем как улучшить)

2021-08-07 15:26 UTC, ademaro commented on src/mock/film.js
>      releaseYear: getRandomInteger(1960, 2021),
зачем год отдельно, если есть поле release?

2021-08-07 15:26 UTC, ademaro commented on src/utils.js
> +export {getRandomInteger, getRandomFloat};
это же только для моков нужно, не?

2021-08-07 15:26 UTC, merged

2021-08-09 13:45 UTC, Tatiaynti commented on src/utils.js
> +export {getRandomInteger, getRandomFloat};
в следующей домашке кладу туда не только моковые данные, поэтому оставила папку вынесенной из mock